# Generated by Django 2.2 on 2022-07-19 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testimonials', '0003_auto_20220719_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(upload_to='testimonials/'),
        ),
    ]
